# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Parot lab"
title:              "Parot lab at Catholic University of Chile"
description:        "this is a page for Vicente Parot lab, we are an applied computational imaging lab at Catholic University of Chile in Santiago, Chile"


# URL
url:                https://vparot.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "blog"
    href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"

collections:
  people:
    output: true
    permalink: /people/:title/index.html
