# Basic
name:               "Parot lab"
title:              "Parot lab at Catholic University of Chile"
description:        "this is a page for Vicente Parot lab, we are an applied computational bioimaging lab at Catholic University of Chile in Santiago, Chile"


# URL
url:                https://vparot.github.io/vparot-klab-test.github.io/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           ""
  - name:           "about"
    href:           "about"
  - name:           "publications"
    href:           "publications"
  - name:           "people"
    href:           "people"
  - name:           "blog"
    href:           "blog"
  - name:           "resources"
    href:           "resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
